### ISSUE TITLE
Direction for v1.3

### ISSUE THREAD

**Issue by CEGLincoln** [AY1920S1-CS2113-T14-2/main#42]
We need a direction for v1.3. Do some clean up and organization so that we can better develop this project. As @saradj shared on Whatsapp:
> i think we need to meet maybe tomorrow after the tut and discuss some changes to do, and fixing  the ones we've done so far cause they seem out of sync

Sticking some comments here:
https://github.com/AY1920S1-CS2113-T14-2/main/pull/38#issuecomment-545380416
https://github.com/AY1920S1-CS2113-T14-2/main/pull/41#issuecomment-545459476

**Comment by JiahanYu** [comment]
ok
